"""
QA Agent Pydantic Models - Data structures for QA workflow graph generation
Similar to UNO's business_function.py but for QA automation
"""

from pydantic import BaseModel, Field
from typing import List, Optional

class QANode(BaseModel):
    """
    Represents a node in the QA workflow graph.
    Each node corresponds to a QA validation step or automation phase.
    """
    id: str = Field(description="Unique identifier for the node (e.g., 'auth_1', 'req_2').")
    type: str = Field(description="Type of the QA agent/node.")
    phase: str = Field(description="QA phase this node belongs to (Discovery, Wireframe, Specification, Build, Test, Deploy).")
    steps: List[int] = Field(description="List of automation steps this node covers (e.g., [1, 2] for steps 1-2).")
    description: str = Field(description="Detailed description of what this QA node validates or automates.")
    query: Optional[str] = Field(None, description="Query or instruction for the QA automation.")
    message: Optional[str] = Field(None, description="Message to display when node completes or needs confirmation.")
    reads: List[str] = Field(default=[], description="List of node IDs whose output is required before processing this node.")
    selenium_function: Optional[str] = Field(None, description="Name of the Selenium function to execute for this node.")
    screenshot_required: bool = Field(default=True, description="Whether to take screenshots during this node execution.")
    document_interaction: bool = Field(default=False, description="Whether this node involves opening/closing documents.")
    validation_type: Optional[str] = Field(None, description="Type of validation (screen_validation, document_validation, process_validation).")
    introduction: Optional[str] = Field(None, description="Introductory message for the node based on the type.")
    guided_step: Optional[str] = Field(None, description="Guided step description for user interface.")
    guided_step_complete: Optional[str] = Field(None, description="Message indicating the guided step completion.")
    transition_prompt: Optional[str] = Field(None, description="Transition prompt to move to next phase.")
    error_handling: Optional[str] = Field(None, description="Specific error handling instructions for this node.")

class QAEdge(BaseModel):
    """
    Represents an edge (transition) between two nodes in the QA workflow graph.
    """
    source: str = Field(description="ID of the source node.")
    target: str = Field(description="ID of the target node.")
    label: Optional[str] = Field(None, description="Label for the edge (SUCCESS, FAILURE, YES, NO).")
    condition: Optional[str] = Field(None, description="Additional condition for following this edge.")

class QAGraph(BaseModel):
    """
    Represents a complete QA workflow graph, composed of nodes and edges.
    Generated by LLM based on the QA automation requirements.
    """
    nodes: List[QANode] = Field(description="List of QA nodes in the graph.")
    edges: List[QAEdge] = Field(description="List of edges defining the QA workflow flow.")
    guided_journey: str = Field(description="Guided journey for the QA automation in markdown format.")
    test_objective: str = Field(description="Overall objective of this QA test automation.")
    expected_duration: str = Field(description="Expected duration for complete QA workflow execution.")
    automation_scope: str = Field(description="Scope of automation covered by this QA workflow.")

class QATestResult(BaseModel):
    """
    Represents the result of a QA test execution.
    """
    node_id: str = Field(description="ID of the node that was executed.")
    success: bool = Field(description="Whether the test step was successful.")
    message: str = Field(description="Result message or error description.")
    screenshot_path: Optional[str] = Field(None, description="Path to screenshot taken during execution.")
    execution_time: float = Field(description="Time taken to execute this step in seconds.")
    validation_details: Optional[dict] = Field(None, description="Additional validation details.")

class QASession(BaseModel):
    """
    Represents a complete QA test session.
    """
    session_id: str = Field(description="Unique session identifier.")
    test_name: str = Field(description="Name of the QA test.")
    graph: QAGraph = Field(description="The QA workflow graph being executed.")
    results: List[QATestResult] = Field(default=[], description="List of test results for each node.")
    start_time: str = Field(description="Session start time in ISO format.")
    end_time: Optional[str] = Field(None, description="Session end time in ISO format.")
    success_rate: float = Field(description="Overall success rate of the QA session.")
    total_screenshots: int = Field(description="Total number of screenshots captured.")
    errors_encountered: int = Field(description="Number of errors encountered during execution.")

class QAConfiguration(BaseModel):
    """
    Configuration for QA automation execution.
    """
    platform_url: str = Field(description="URL of the platform to test.")
    username: str = Field(description="Username for authentication.")
    password: str = Field(description="Password for authentication.")
    browser_type: str = Field(default="chrome", description="Browser type for automation.")
    headless: bool = Field(default=False, description="Whether to run browser in headless mode.")
    screenshot_on_error: bool = Field(default=True, description="Whether to take screenshots on errors.")
    screenshot_on_success: bool = Field(default=True, description="Whether to take screenshots on success.")
    wait_timeout: int = Field(default=10, description="Default wait timeout in seconds.")
    retry_attempts: int = Field(default=3, description="Number of retry attempts for failed operations.")
    results_directory: str = Field(description="Directory to store test results and screenshots.")

class QAPromptContext(BaseModel):
    """
    Context information for generating QA workflow graphs via LLM.
    """
    test_objective: str = Field(description="What the QA automation should achieve.")
    application_type: str = Field(description="Type of application being tested (e.g., 'Vacation Request App').")
    automation_phases: List[str] = Field(description="List of phases to automate (Discovery, Wireframe, etc.).")
    selenium_functions: List[str] = Field(description="Available Selenium automation functions.")
    validation_requirements: List[str] = Field(description="Specific validation requirements.")
    error_scenarios: List[str] = Field(description="Expected error scenarios to handle.")
    screenshot_points: List[str] = Field(description="Points where screenshots should be captured.")
    document_interactions: List[str] = Field(description="Documents that need to be opened/validated.")
    expected_steps: int = Field(description="Expected number of automation steps.")
    time_constraints: Optional[str] = Field(None, description="Any time constraints for the automation.")